# Generated by Django 5.1.3 on 2024-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0002_user_is_authorized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_authorized",
            field=models.BooleanField(default=False),
        ),
    ]
